apk := 'build/outputs/apk/debug/cli-debug.apk'
package := 'dev.mpclipboard.android.cli'

build:
    mise build:android-cli

install:
    adb install -r {{apk}}

run host token name:
    adb shell 'APK=$(pm path {{package}} | sed "s/package://"); CLASSPATH=$APK app_process /system/bin dev.mpclipboard.android.cli.Main {{host}} {{token}} {{name}}'
