# Generates xcode workspace
[macos]
generate:
    @just generate-all-resources
    xcodegen generate

# Builds. An argument is either "Debug" or "Release"
[macos]
[arg('configuration', pattern='Debug|Release')]
build configuration:
    xcodebuild -configuration {{configuration}}

# Runs pre-build app. An argument is either "Debug" or "Release"
[macos]
[arg('configuration', pattern='Debug|Release')]
run configuration:
    ./build/{{configuration}}/mpclipboard.app/Contents/MacOS/mpclipboard

# Re-builds everything in "Debug" mode and launches
[macos]
dev:
    cd ../generic-client && cargo build
    @just build Debug
    @just run Debug

# Builds a release and places it at given "out" argument
[macos]
release out:
    @just clean
    @just generate
    cd ../generic-client && cargo build --release
    @just build Release

    cd build/Release && \
        rm -rf dmg-root mpclipboard.dmg && \
        mkdir -p dmg-root && \
        cp -R mpclipboard.app dmg-root/ && \
        ln -s /Applications dmg-root/Applications && \
        hdiutil create -volname mpclipboard -srcfolder dmg-root -ov -format UDZO mpclipboard.dmg

    mv build/Release/mpclipboard.dmg {{out}}

# Removes build artifacts
clean:
    rm -rf build
    rm -rf dmg-root
    rm -rf mpclipboard.xcodeproj
    rm -f mpclipboard.app.zip

# Schedules build on CI
upload version ref="master":
    gh workflow run release-macos --ref {{ref}} -f version={{version}}

baseicon := '../icon_512x512.png'
assetsdir := 'Assets.xcassets'

_generate-asset-contents-json:
    ./scripts/generate-asset-contents-json.py

_generate-imageset-variant rgb density size outpath:
    magick {{baseicon}} \
        -density {{density}} \
        -resize {{size}} \
        -alpha set \
        -channel rgba \
        -fill "{{rgb}}" \
        -colorize 100% \
        -strip \
        {{outpath}}

_generate-imageset name rgb:
    mkdir -p {{assetsdir}}/{{name}}.imageset

    @just _generate-imageset-variant "{{rgb}}" 72  24x24 {{assetsdir}}/{{name}}.imageset/{{name}}.png
    @just _generate-imageset-variant "{{rgb}}" 144 48x48 {{assetsdir}}/{{name}}.imageset/{{name}}@2x.png
    @just _generate-imageset-variant "{{rgb}}" 216 72x72 {{assetsdir}}/{{name}}.imageset/{{name}}@3x.png

_generate-icon-variant rgb size outpath:
    magick {{baseicon}} \
        -resize {{size}} \
        -alpha set \
        -channel rgba \
        -fill "{{rgb}}" \
        -colorize 100% \
        -strip \
        {{outpath}}

_generate-iconset rgb:
    mkdir -p {{assetsdir}}/AppIcon.appiconset

    @just _generate-icon-variant "{{rgb}}" 16x16     {{assetsdir}}/AppIcon.appiconset/icon-16x16.png
    @just _generate-icon-variant "{{rgb}}" 32x32     {{assetsdir}}/AppIcon.appiconset/icon-16x16@2x.png
    @just _generate-icon-variant "{{rgb}}" 32x32     {{assetsdir}}/AppIcon.appiconset/icon-32x32.png
    @just _generate-icon-variant "{{rgb}}" 64x64     {{assetsdir}}/AppIcon.appiconset/icon-32x32@2x.png
    @just _generate-icon-variant "{{rgb}}" 128x128   {{assetsdir}}/AppIcon.appiconset/icon-128x128.png
    @just _generate-icon-variant "{{rgb}}" 256x256   {{assetsdir}}/AppIcon.appiconset/icon-128x128@2x.png
    @just _generate-icon-variant "{{rgb}}" 256x256   {{assetsdir}}/AppIcon.appiconset/icon-256x256.png
    @just _generate-icon-variant "{{rgb}}" 512x512   {{assetsdir}}/AppIcon.appiconset/icon-256x256@2x.png
    @just _generate-icon-variant "{{rgb}}" 512x512   {{assetsdir}}/AppIcon.appiconset/icon-512x512.png
    @just _generate-icon-variant "{{rgb}}" 1024x1024 {{assetsdir}}/AppIcon.appiconset/icon-512x512@2x.png

# Generates all image/icon resources
generate-all-resources:
    @just _generate-asset-contents-json
    @just _generate-imageset green  "rgb(23, 199, 23)"
    @just _generate-imageset red    "rgb(195, 40, 40)"
    @just _generate-imageset yellow "rgb(236, 223, 41)"

    @just _generate-iconset "rgb(55, 54, 46)"
