[package]
name = "mpclipboard-server"
version = "0.1.0"
edition = "2024"
authors = ["Ilya Bylich"]
license = "MIT"
description = "MPClipboard server"

[dependencies]
anyhow = "1"
env_logger = { version = "0.11", default-features = false, features = [
    "color",
] }
mpclipboard-shared = { path = "../shared" }
rustix = { version = "1.1.4", features = ["event", "net", "time"] }

[package.metadata.deb]
assets = [
    [
        "target/release/mpclipboard-server",
        "usr/bin/mpclipboard-server",
        "755",
    ],
    [
        "debian/mpclipboard-server.service",
        "lib/systemd/system/mpclipboard-server.service",
        "644",
    ],
]
extended-description = ""
