lib := '../generic-client/target/debug/libmpclipboard_generic_client.a'

dev-macos log="info":
    cd ../generic-client && cargo build
    clang -fuse-ld=lld poll-cli.c {{lib}} -framework Security -framework CoreFoundation -o poll-cli
    RUST_LOG_STYLE=always RUST_LOG={{log}} ./poll-cli

dev-linux log="info":
    cd ../generic-client && cargo build
    clang -fuse-ld=lld poll-cli.c {{lib}} -o poll-cli
    RUST_LOG_STYLE=always RUST_LOG={{log}} ./poll-cli
