[package]
name = "mpclipboard-generic-client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
anyhow = "1.0"
rustls-platform-verifier = "0.7"
rustls = { version = "0.23", features = ["ring"] }
libc = "0.2"
rustix = { version = "1", features = ["net", "time"] }
mpclipboard-shared = { path = "../shared" }
epoll = "4.4"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15"
jni = { version = "0.22", default-features = false }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
env_logger = { version = "0.11", default-features = false, features = [
    "color",
] }
