[package]
name = "mpclipboard-client"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "MPClipboard client for Linux"
authors = ["Ilya Bylich"]

[dependencies]
ksni = { version = "0.3" }
log = "0.4"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
wl-data-control-protocol-evt = { version = "1" }

mpclipboard-generic-client = { path = "../generic-client" }

[package.metadata.deb]
assets = [
    [
        "target/release/mpclipboard-client",
        "usr/bin/mpclipboard-client",
        "755",
    ],
    [
        "debian/mpclipboard-client.service",
        "usr/lib/systemd/user/mpclipboard-client.service",
        "644",
    ],
]
extended-description = ""
