name: release-macos

on:
  workflow_dispatch:
    inputs:
      version:
        description: release version in MAJOR.MINOR.PATCH version
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: brew install xcodegen imagemagick

      # - run: find /Applications -name "Xcode*.app" -type d
      - run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
      - run: just macos::release $PWD/mpclipboard_${{ inputs.version }}.dmg

      - uses: ./.github/actions/release
        with:
          filename: mpclipboard_${{ inputs.version }}.dmg
          own-release-name: macos-v${{ inputs.version }}
          previous-files-pattern: mpclipboard_*.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
